//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uspostalcodes
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.counties = new HashSet<county>();
        }
    
        public int state_id { get; set; }
        public string state_name { get; set; }
        public string state_abbr { get; set; }
    
        public virtual ICollection<county> counties { get; set; }
    }
}
