INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Alabama','AL');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Alaska','AK');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Arizona','AZ');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Arkansas','AR');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('California','CA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Colorado','CO');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Connecticut','CT');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Delaware','DE');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Florida','FL');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Georgia','GA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Hawaii','HI');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Idaho','ID');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Illinois','IL');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Indiana','IN');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Iowa','IA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Kansas','KS');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Kentucky','KY');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Louisiana','LA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Maine','ME');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Maryland','MD');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Massachusetts','MA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Michigan','MI');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Minnesota','MN');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Mississippi','MS');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Missouri','MO');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Montana','MT');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Nebraska','NE');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Nevada','NV');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('New Hampshire','NH');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('New Jersey','NJ');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('New Mexico','NM');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('New York','NY');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('North Carolina','NC');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('North Dakota','ND');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Ohio','OH');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Oklahoma','OK');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Oregon','OR');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Pennsylvania','PA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Rhode Island','RI');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('South Carolina','SC');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('South Dakota','SD');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Tennessee','TN');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Texas','TX');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Utah','UT');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Vermont','VT');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Virginia','VA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Washington','WA');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('West Virginia','WV');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Wisconsin','WI');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Wyoming','WY');
INSERT INTO [dbo].[states]([state_name],[state_abbr]) VALUES ('Washington DC','DC');
